---
registries:
  mirrors:
    docker.io:
      endpoint:
        - "https://registry.example.com"
      rewrite:
        "(.*)": "docker.io/$1"
    quay.io:
      endpoint:
        - "https://registry.example.com"
      rewrite:
        "(.*)": "quay.io/$1"
    gcr.io:
      endpoint:
        - "https://registry.example.com"
      rewrite:
        "(.*)": "gcr.io/$1"
    k8s.gcr.io:
      endpoint:
        - "https://registry.example.com"
      rewrite:
        "(.*)": "k8s.gcr.io/$1"
    registry.k8s.io:
      endpoint:
        - "https://registry.example.com"
      rewrite:
        "(.*)": "registry.k8s.io/$1"
    registry.rancher.com:
      endpoint:
        - "https://registry.example.com"
      rewrite:
        "(.*)": "registry.rancher.com/$1"
    registry.suse.com:
      endpoint:
        - "https://registry.example.com"
      rewrite:
        "(.*)": "registry.suse.com/$1"
    ghcr.io:
      endpoint:
        - "https://registry.example.com"
      rewrite:
        "(.*)": "ghcr.io/$1"
    dp.apps.rancher.io:
      endpoint:
        - https://registry.example.com/v2
      rewrite:
        (.*): dp.apps.rancher.io/$1
